package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

const (
	KeyAWSRegion     = "defaults.aws_region"
	KeyKubeNamespace = "defaults.kube_namespace"
	KeySSHUsername   = "defaults.ssh_username"

	// KeyAuthProvider selects the active identity provider.
	// Valid values: "okta", "ping", "oidc", "ldap", "aws-sso", "github", "apikey".
	KeyAuthProvider = "auth.provider"

	// KeyAuthToken is the static token for the apikey provider.
	// Also read from the DEVCTL_TOKEN environment variable.
	KeyAuthToken = "auth.token"

	// OIDC provider config keys (also used by okta/ping profiles).
	KeyOIDCIssuerURL    = "auth.oidc.issuer_url"
	KeyOIDCClientID     = "auth.oidc.client_id"
	KeyOIDCClientSecret = "auth.oidc.client_secret"

	// Okta provider config keys.
	KeyOktaDomain       = "auth.okta.domain"
	KeyOktaClientID     = "auth.okta.client_id"
	KeyOktaClientSecret = "auth.okta.client_secret"

	// PingID / PingFederate provider config keys.
	KeyPingIssuerURL    = "auth.ping.issuer_url"
	KeyPingClientID     = "auth.ping.client_id"
	KeyPingClientSecret = "auth.ping.client_secret"

	// LDAP / Active Directory provider config keys.
	// Bind password is never stored in config — use DEVCTL_LDAP_BIND_PASSWORD env var.
	KeyLDAPHost       = "auth.ldap.host"
	KeyLDAPPort       = "auth.ldap.port"
	KeyLDAPUseTLS     = "auth.ldap.use_tls"
	KeyLDAPBaseDN     = "auth.ldap.base_dn"
	KeyLDAPBindDN     = "auth.ldap.bind_dn"
	KeyLDAPUserFilter = "auth.ldap.user_filter"
)

// Template is written by "devctl config init".
const Template = `# devctl configuration file
# Generated by: devctl config init
#
# Priority order for each value:
#   explicit CLI flag > environment variable > this file

defaults:
  # AWS default region. Also read from AWS_REGION / AWS_DEFAULT_REGION.
  aws_region: ""

  # Default Kubernetes namespace for kube commands.
  kube_namespace: ""

  # Default SSH username for the aws ssh-ec2 command.
  ssh_username: ec2-user

# Authentication — choose one provider and configure it below.
# auth:
#   provider: okta   # okta | ping | oidc | ldap | aws-sso | github | apikey
#
#   okta:
#     domain: myorg.okta.com
#     client_id: ""
#
#   ping:
#     issuer_url: https://ping.myorg.com/as
#     client_id: ""
#
#   oidc:
#     issuer_url: https://your-idp.example.com
#     client_id: ""
#     scopes: [openid, profile, email, offline_access]
#
#   ldap:
#     host: ldap.corp.example.com
#     port: 636             # 636 for LDAPS (use_tls: true) or 389 for StartTLS
#     use_tls: true         # true = LDAPS; false = StartTLS on plain connection
#     base_dn: DC=corp,DC=example,DC=com
#     bind_dn: CN=devctl-svc,OU=ServiceAccounts,DC=corp,DC=example,DC=com
#     user_filter: "(&(objectClass=user)(sAMAccountName=%s))"
#     # Bind password: set DEVCTL_LDAP_BIND_PASSWORD env var — never store in config file
#
#   aws_sso:
#     start_url: https://myorg.awsapps.com/start
#     region: us-east-1
#
#   github:
#     client_id: ""
#     base_url: https://github.com
#
#   # apikey: set DEVCTL_TOKEN env var or auth.token below (CI/CD use)
#   token: ""
`

// Init loads configuration in the following priority order:
//  1. cfgFile (from --config flag)
//  2. .devctl.yaml in the current working directory
//  3. ~/.devctl/config.yaml
//
// A missing config file is silently ignored. A malformed file prints a warning
// to stderr but does not cause the process to exit.
func Init(cfgFile string) error {
	v := viper.GetViper()

	// Env var support: DEVCTL_DEFAULTS_AWS_REGION, etc.
	v.SetEnvPrefix("DEVCTL")
	v.AutomaticEnv()

	// Also honour the standard AWS env vars for aws_region.
	v.BindEnv(KeyAWSRegion, "AWS_REGION", "AWS_DEFAULT_REGION", "DEVCTL_DEFAULTS_AWS_REGION") //nolint:errcheck
	// DEVCTL_TOKEN maps to the apikey provider's token config key.
	v.BindEnv(KeyAuthToken, "DEVCTL_TOKEN") //nolint:errcheck

	switch {
	case cfgFile != "":
		v.SetConfigFile(cfgFile)
	case fileExists(".devctl.yaml"):
		v.SetConfigFile(".devctl.yaml")
	default:
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("resolve home directory: %w", err)
		}
		v.SetConfigFile(filepath.Join(home, ".devctl", "config.yaml"))
	}

	if err := v.ReadInConfig(); err != nil {
		// A missing config file is not an error — it is optional.
		if !errors.Is(err, os.ErrNotExist) && !isNotFound(err) {
			fmt.Fprintf(os.Stderr, "warning: could not read config file: %v\n", err)
		}
	}

	return nil
}

// GetString returns the viper value for key, falling back to fallback when
// the resolved value is empty.
func GetString(key, fallback string) string {
	if v := viper.GetString(key); v != "" {
		return v
	}
	return fallback
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// isNotFound reports whether err is a viper "config file not found" error.
// Viper wraps the underlying fs error differently depending on whether
// SetConfigFile or AddConfigPath was used, so we check both.
func isNotFound(err error) bool {
	var notFound viper.ConfigFileNotFoundError
	return errors.As(err, &notFound)
}
