package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/viper"
)

const (
	KeyAWSRegion     = "defaults.aws_region"
	KeyAWSProfile    = "defaults.aws_profile"
	KeyKubeNamespace = "defaults.kube_namespace"
	KeyKubeContext   = "defaults.kube_context"
	KeySSHUsername   = "defaults.ssh_username"

	// KeyDefaultProfile holds the name of the active profile ("default_profile" in config file).
	KeyDefaultProfile = "default_profile"

	// KeyAuthProvider selects the active identity provider.
	// Valid values: "okta", "ping", "oidc", "ldap", "aws-sso", "github", "apikey".
	KeyAuthProvider = "auth.provider"

	// KeyAuthToken is the static token for the apikey provider.
	// Also read from the DEVCTL_TOKEN environment variable.
	KeyAuthToken = "auth.token"

	// OIDC provider config keys (also used by okta/ping profiles).
	KeyOIDCIssuerURL    = "auth.oidc.issuer_url"
	KeyOIDCClientID     = "auth.oidc.client_id"
	KeyOIDCClientSecret = "auth.oidc.client_secret"

	// Okta provider config keys.
	KeyOktaDomain       = "auth.okta.domain"
	KeyOktaClientID     = "auth.okta.client_id"
	KeyOktaClientSecret = "auth.okta.client_secret"

	// PingID / PingFederate provider config keys.
	KeyPingIssuerURL    = "auth.ping.issuer_url"
	KeyPingClientID     = "auth.ping.client_id"
	KeyPingClientSecret = "auth.ping.client_secret"

	// LDAP / Active Directory provider config keys.
	// Bind password is never stored in config — use DEVCTL_LDAP_BIND_PASSWORD env var.
	KeyLDAPHost       = "auth.ldap.host"
	KeyLDAPPort       = "auth.ldap.port"
	KeyLDAPUseTLS     = "auth.ldap.use_tls"
	KeyLDAPBaseDN     = "auth.ldap.base_dn"
	KeyLDAPBindDN     = "auth.ldap.bind_dn"
	KeyLDAPUserFilter = "auth.ldap.user_filter"

	// AWS IAM Identity Center (SSO) provider config keys.
	KeyAWSSOStartURL  = "auth.aws_sso.start_url"
	KeyAWSSORegion    = "auth.aws_sso.region"
	KeyAWSSOAccountID = "auth.aws_sso.account_id"
	KeyAWSSSORoleName = "auth.aws_sso.role_name"

	// GitHub OAuth Device Flow provider config keys.
	KeyGitHubClientID = "auth.github.client_id"
	KeyGitHubBaseURL  = "auth.github.base_url"
)

// Template is written by "devctl config init".
const Template = `# devctl configuration file
# Generated by: devctl config init
#
# Priority order for each value:
#   explicit CLI flag > environment variable > active profile > defaults block

defaults:
  # AWS default region. Also read from AWS_REGION / AWS_DEFAULT_REGION.
  aws_region: ""

  # AWS credentials profile (~/.aws/credentials). Also read from AWS_PROFILE.
  aws_profile: ""

  # Default Kubernetes namespace for kube commands. Also read from DEVCTL_NAMESPACE.
  kube_namespace: ""

  # Default Kubernetes context. Overrides the current context in ~/.kube/config.
  kube_context: ""

  # Default SSH username for the aws ssh-ec2 command.
  ssh_username: ec2-user

# Named profiles — select with: devctl --profile <name>
# Set a persistent default with: devctl profile use <name>
# default_profile: dev

# profiles:
#   dev:
#     aws_region: us-east-1
#     aws_profile: dev-account
#     kube_context: dev-cluster
#     kube_namespace: dev
#   prod:
#     aws_region: eu-west-1
#     aws_profile: prod-account
#     kube_context: prod-cluster
#     kube_namespace: production

# Authentication — choose one provider and configure it below.
# auth:
#   provider: okta   # okta | ping | oidc | ldap | aws-sso | github | apikey
#
#   okta:
#     domain: myorg.okta.com
#     client_id: ""
#
#   ping:
#     issuer_url: https://ping.myorg.com/as
#     client_id: ""
#
#   oidc:
#     issuer_url: https://your-idp.example.com
#     client_id: ""
#     scopes: [openid, profile, email, offline_access]
#
#   ldap:
#     host: ldap.corp.example.com
#     port: 636             # 636 for LDAPS (use_tls: true) or 389 for StartTLS
#     use_tls: true         # true = LDAPS; false = StartTLS on plain connection
#     base_dn: DC=corp,DC=example,DC=com
#     bind_dn: CN=devctl-svc,OU=ServiceAccounts,DC=corp,DC=example,DC=com
#     user_filter: "(&(objectClass=user)(sAMAccountName=%s))"
#     # Bind password: set DEVCTL_LDAP_BIND_PASSWORD env var — never store in config file
#
#   aws_sso:
#     start_url: https://myorg.awsapps.com/start
#     region: us-east-1
#     account_id: "123456789012"  # optional: shown in auth status
#     role_name: DevAccess         # optional: auto-fetch role credentials after login
#
#   github:
#     client_id: "Iv1.abc123"
#     base_url: https://github.com   # override for GitHub Enterprise Server
#
#   # apikey: set DEVCTL_TOKEN env var or auth.token below (CI/CD use)
#   token: ""
`

// Init loads configuration in the following priority order:
//  1. cfgFile (from --config flag)
//  2. .devctl.yaml in the current working directory
//  3. ~/.devctl/config.yaml
//
// A missing config file is silently ignored. A malformed file prints a warning
// to stderr but does not cause the process to exit.
func Init(cfgFile string) error {
	v := viper.GetViper()

	// Env var support: DEVCTL_DEFAULTS_AWS_REGION, etc.
	v.SetEnvPrefix("DEVCTL")
	v.AutomaticEnv()

	// Also honour the standard AWS env vars for aws_region and aws_profile.
	v.BindEnv(KeyAWSRegion, "AWS_REGION", "AWS_DEFAULT_REGION", "DEVCTL_DEFAULTS_AWS_REGION")   //nolint:errcheck
	v.BindEnv(KeyAWSProfile, "AWS_PROFILE", "DEVCTL_DEFAULTS_AWS_PROFILE")                       //nolint:errcheck
	// DEVCTL_NAMESPACE (or the prefixed form) overrides the kube namespace.
	v.BindEnv(KeyKubeNamespace, "DEVCTL_NAMESPACE", "DEVCTL_DEFAULTS_KUBE_NAMESPACE") //nolint:errcheck
	// DEVCTL_TOKEN maps to the apikey provider's token config key.
	v.BindEnv(KeyAuthToken, "DEVCTL_TOKEN") //nolint:errcheck

	// Viper-level default for ssh_username so the value flows through the config
	// resolution chain (CLI flag > env var > config file > this default) rather
	// than being hardcoded in the command handler.
	v.SetDefault(KeySSHUsername, "ec2-user")

	switch {
	case cfgFile != "":
		v.SetConfigFile(cfgFile)
	case fileExists(".devctl.yaml"):
		v.SetConfigFile(".devctl.yaml")
	default:
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("resolve home directory: %w", err)
		}
		v.SetConfigFile(filepath.Join(home, ".devctl", "config.yaml"))
	}

	if err := v.ReadInConfig(); err != nil {
		// A missing config file is not an error — it is optional.
		if !errors.Is(err, os.ErrNotExist) && !isNotFound(err) {
			fmt.Fprintf(os.Stderr, "warning: could not read config file: %v\n", err)
		}
	}

	return nil
}

// ApplyProfile overlays profile values onto the defaults namespace.
// If explicit is empty, the default_profile key from the config file is used.
// An empty explicit with no default_profile set is a no-op.
// Env-var-bound keys are always skipped so that env vars win over profiles.
func ApplyProfile(explicit string) error {
	profileName := explicit
	if profileName == "" {
		profileName = viper.GetString(KeyDefaultProfile)
	}
	if profileName == "" {
		return nil
	}

	profiles := viper.GetStringMap("profiles")
	if _, ok := profiles[profileName]; !ok {
		available := AvailableProfiles()
		if len(available) == 0 {
			return fmt.Errorf("profile %q not found; no profiles are defined in the config file", profileName)
		}
		return fmt.Errorf("profile %q not found; available profiles: %s",
			profileName, strings.Join(available, ", "))
	}

	// apply overlays each profile sub-key onto the defaults namespace, but only
	// when the corresponding env vars are not set (env always wins).
	apply := func(viperKey, profileSubkey string, envVars ...string) {
		val := viper.GetString(fmt.Sprintf("profiles.%s.%s", profileName, profileSubkey))
		if val == "" {
			return
		}
		for _, e := range envVars {
			if os.Getenv(e) != "" {
				return
			}
		}
		viper.Set(viperKey, val)
	}

	apply(KeyAWSRegion, "aws_region", "AWS_REGION", "AWS_DEFAULT_REGION", "DEVCTL_DEFAULTS_AWS_REGION")
	apply(KeyAWSProfile, "aws_profile", "AWS_PROFILE", "DEVCTL_DEFAULTS_AWS_PROFILE")
	apply(KeyKubeNamespace, "kube_namespace", "DEVCTL_NAMESPACE", "DEVCTL_DEFAULTS_KUBE_NAMESPACE")
	apply(KeyKubeContext, "kube_context")

	// Record the active profile name so ActiveProfile() can report it.
	viper.Set(KeyDefaultProfile, profileName)
	return nil
}

// ActiveProfile returns the name of the currently active profile (empty if none).
func ActiveProfile() string {
	return viper.GetString(KeyDefaultProfile)
}

// AvailableProfiles returns the names of all configured profiles, sorted.
func AvailableProfiles() []string {
	profiles := viper.GetStringMap("profiles")
	names := make([]string, 0, len(profiles))
	for name := range profiles {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// SetDefaultProfile writes default_profile: <name> to the config file and
// updates the in-memory viper state.
func SetDefaultProfile(name string) error {
	viper.Set(KeyDefaultProfile, name)
	return viper.WriteConfig()
}

// GetString returns the viper value for key, falling back to fallback when
// the resolved value is empty.
func GetString(key, fallback string) string {
	if v := viper.GetString(key); v != "" {
		return v
	}
	return fallback
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// isNotFound reports whether err is a viper "config file not found" error.
// Viper wraps the underlying fs error differently depending on whether
// SetConfigFile or AddConfigPath was used, so we check both.
func isNotFound(err error) bool {
	var notFound viper.ConfigFileNotFoundError
	return errors.As(err, &notFound)
}
